/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia;

import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class FrmEditarMedicamento extends javax.swing.JFrame {
    ConsultasBD consulta = new ConsultasBD();

    /**
     * Creates new form FrmEditarMedicamento
     */
    public FrmEditarMedicamento() {
        initComponents();
        txtIDProducto.setText(""+Globales.medicamentoG.getId_Medicamento());
        txtCaducidad.setText(Globales.medicamentoG.getCaducidad());
        txtCondicionVenta.setText(Globales.medicamentoG.getCondicionVenta());
        txtFabricante.setText(Globales.medicamentoG.getFabricante());
        txtFomrmaFarmaceutica.setText(Globales.medicamentoG.getFormaFarmaceutica());
        txtMarcaComercial.setText(Globales.medicamentoG.getNombreComercial());
        txtNombreGenerico.setText(Globales.medicamentoG.getNombreGenerico());
        txtPrecio.setText(""+Globales.medicamentoG.getPrecio());
        txtPresentacion.setText(Globales.medicamentoG.getPresentacion());
        txtStock.setText(""+Globales.medicamentoG.getStock());
        
    }
    
    public void cerrar(){
        FrmVerMedicamentos frm = new FrmVerMedicamentos();
        frm.setVisible(true);
        this.dispose();
    }
    
    public boolean verificarCajas(){
        try {
            if (txtCaducidad.getText().compareTo("") == 0){
                JOptionPane.showMessageDialog(null, "Campos vacios !!");
                return false;
            }
            if (txtCondicionVenta.getText().compareTo("") == 0){
                JOptionPane.showMessageDialog(null, "Campos vacios !!");
                return false;
            }
            if (txtFabricante.getText().compareTo("") == 0){
                JOptionPane.showMessageDialog(null, "Campos vacios !!");
                return false;
            }
            if (txtFomrmaFarmaceutica.getText().compareTo("") == 0){
                JOptionPane.showMessageDialog(null, "Campos vacios !!");
                return false;
            }
            if (txtIDProducto.getText().compareTo("") == 0){
                JOptionPane.showMessageDialog(null, "Campos vacios !!");
                return false;
            }
            if (txtMarcaComercial.getText().compareTo("") == 0){
                JOptionPane.showMessageDialog(null, "Campos vacios !!");
                return false;
            }
            if (txtNombreGenerico.getText().compareTo("") == 0){
                JOptionPane.showMessageDialog(null, "Campos vacios !!");
                return false;
            }
            if (txtPrecio.getText().compareTo("") == 0){
                JOptionPane.showMessageDialog(null, "Campos vacios !!");
                return false;
            }
            if (txtPresentacion.getText().compareTo("") == 0){
                JOptionPane.showMessageDialog(null, "Campos vacios !!");
                return false;
            }
            if (txtStock.getText().compareTo("") == 0){
                JOptionPane.showMessageDialog(null, "Campos vacios !!");
                return false;
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Verificar campo para numeros!");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtIDProducto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMarcaComercial = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNombreGenerico = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPresentacion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFomrmaFarmaceutica = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCondicionVenta = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCaducidad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtFabricante = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editar Datos de Medicamento");

        jLabel5.setText("id_producto");

        jLabel6.setText("Nombre Comercial");

        jLabel7.setText("Nombre Generico");

        jLabel8.setText("Presentacion");

        jLabel9.setText("Forma Farmaceutica");

        jLabel10.setText("Condicion Venta");

        jLabel11.setText("Caducidad");

        jLabel12.setText("Fabricante");

        jLabel13.setText("Stock");

        jLabel14.setText("Precio");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(txtIDProducto)
                                .addComponent(txtMarcaComercial)
                                .addComponent(txtNombreGenerico)
                                .addComponent(txtPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtFomrmaFarmaceutica, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(txtCondicionVenta)
                            .addComponent(jLabel14)
                            .addComponent(txtCaducidad)
                            .addComponent(txtFabricante)
                            .addComponent(txtStock)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCondicionVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarcaComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreGenerico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFomrmaFarmaceutica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        cerrar();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (!verificarCajas()){
            return;
        }
        try {
            int idMedicamento = Integer.parseInt(txtIDProducto.getText());
            String marcaComercial = txtMarcaComercial.getText().toUpperCase();
            String nombreGenerico = txtNombreGenerico.getText().toUpperCase();
            String presentacion = txtPresentacion.getText().toUpperCase();
            String formaFarmaceutica = txtFomrmaFarmaceutica.getText().toUpperCase();
            String condicionVenta = txtCondicionVenta.getText().toUpperCase();
            String caducidad = txtCaducidad.getText().toUpperCase();
            String fabricante = txtFabricante.getText().toUpperCase();
            int stock = Integer.parseInt(txtStock.getText());
            int precio = Integer.parseInt(txtPrecio.getText());
            
            consulta.modificarMedicamento(
                    idMedicamento, 
                    marcaComercial, 
                    nombreGenerico, 
                    presentacion, 
                    formaFarmaceutica, 
                    condicionVenta, 
                    caducidad, 
                    fabricante, 
                    stock, 
                    precio);
            cerrar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe escribir numeros!!");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditarMedicamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCaducidad;
    private javax.swing.JTextField txtCondicionVenta;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JTextField txtFomrmaFarmaceutica;
    private javax.swing.JTextField txtIDProducto;
    private javax.swing.JTextField txtMarcaComercial;
    private javax.swing.JTextField txtNombreGenerico;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPresentacion;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
